### ISSUE TITLE
Expression Query Failing

### ISSUE THREAD

**Issue by michal-g** [bmeg/bmeg#41]
for query:
`oph.query().has("gid", "cohort:TCGA-BRCA").outgoing("hasSample").mark("sample").incoming("expressionFor").mark("expression").select(["sample", "expression"])`

`.count().execute()` returns 888 (and so the query is non-empty)

but `.execute()` returns `<HEAD><TITLE>Connection Timed Out</TITLE></HEAD>`

**Comment by kellrott** [comment]
Does it work if you add a `.limit(5)` ?

**Comment by prismofeverything** [comment]
It is fixed now.

**Comment by kellrott** [comment]
What was the issue?

**Comment by prismofeverything** [comment]
I was doing a bunch of ingestion and reduced the memory footprint to fit as
many processes on the machine at once. When I started the server I forgot
to put the memory back, so it ran out of RAM immediately on getting
requests.
