### ISSUE TITLE
ITCR Link

### ISSUE THREAD

**Issue by kellrott** [bmeg/bmeg#42]
Add link back to ITCR about funding

**Comment by kellrott** [comment]
Project ID: 1R01CA180778-01

http://grantome.com/grant/NIH/R01-CA180778-01

**Comment by kellrott** [comment]
ITCR Home: https://itcr.nci.nih.gov

**Comment by prismofeverything** [comment]
New footer: 
![screen shot 2018-03-26 at 6 52 24 pm](https://user-images.githubusercontent.com/9079/37942210-e90e673c-3126-11e8-9e53-6948c7c6d21e.png)
