### ISSUE TITLE
sampleOf Edge Malfunctioning

### ISSUE THREAD

**Issue by michal-g** [bmeg/bmeg#43]
`oph.query().has("gid", "project:TCGA-BRCA").outgoing("hasMember").count().execute()` -> `1083`
(we can find individuals belonging to a project)

`oph.query().has("gid", "cohort:TCGA-BRCA").outgoing("hasSample").count().execute()` -> `1938`
(we can find the sample belonging to the individuals in a project)

`oph.query().has("gid", "project:TCGA-BRCA").outgoing("hasMember").incoming('sampleOf').count().execute()` -> `0`
(we cannot find the edges that link the samples in a project to the individuals they came from)

**Comment by prismofeverything** [comment]
This is fixed, it turns out the cause was all the protograph translations were run on a machine that ran out of disk space, so not all of the data was generated. Rerunning the protograph translations fixed the problem.
